# Generated by Django 2.1.1 on 2018-10-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181014_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
